# url: "https://www.controlledflight.ca"
url: "https://irvingreid.github.io/controlledflight-jekyll"
title: "Controlled Flight Into Terrain"
description: "Everything was going just fine until we ran into the real world"

author: "Irving Reid"

social:
  github: https://github.com/irvingreid
  mastodon: https://hachyderm.io/@irvingreid

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass

theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate


permalink:      /:year/:month/:day/:title
paginate_path: /page/:num/
paginate:       10

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /category/:name/
    tag: /tags/:name/

# Links to social media
social:
  github: https://github.com/irvingreid
  mastodon: https://hachyderm.io/@irvingreid
  linkedin: https://www.linkedin.com/in/irving-reid/
